// backend\src\models\websiteSetting.model.js
import db from "../config/db.js";

export const getSiteSetting = async () => {
  const [rows] = await db.query("SELECT * FROM website_setting WHERE id=1");
  return rows[0];
};

export const updateSiteSetting = async (data) => {
  const {
    site_name,
    admin_name,
    user_image,
    facebook,
    instagram,
    twitter,
    telegram,
    youtube,
    linkedin,
    email,
    email2,
    whatsapp,
    mobile,
    mobile2,
    address,
    address2,
    abouttitle,
    aboutSubtitle,
    aboutTagline,
    aboutimg,
    aboutimg_title,
    aboutimg_alt,
    aboutdec,
    homeslider_title,
    homeslider_subtitle,
    homeslider_tagline,
    yearsOf_experience,
    happy_customers,
    completed_construction,
    logo,
    logoimg_title,
    logoimg_alt,
    footerlogo,
    footerlogo_title,
    footerlogo_alt,
    favicon,
    copyright,
    footer_content,
    address_map,
    terms_condition,
    return_policy,
    privacy_policy,
    meta_title,
    meta_keyword,
    meta_description,
    ip_address,
    updated_by,
  } = data;
  await db.query(
    `UPDATE website_setting
     SET  site_name=?,admin_name=?, user_image=?, facebook=?, instagram=?, twitter=?, telegram=?, youtube=?, linkedin=?, email=?, email2=?, whatsapp=?, mobile=?, mobile2=?, address=?, address2=?, abouttitle=?, aboutSubtitle=?, aboutTagline=?, aboutimg=?, aboutimg_title=?, aboutimg_alt=?, aboutdec=?, homeslider_title=?, homeslider_subtitle=?, homeslider_tagline=?, yearsOf_experience=?, happy_customers=?, completed_construction=?, logo=?, logoimg_title=?, logoimg_alt=?, footerlogo=?, footerlogo_title=?, footerlogo_alt=?, favicon=?, copyright=?, footer_content=?, address_map=?, terms_condition=?, return_policy=?, privacy_policy=?, meta_title=?, meta_keyword=?, meta_description=?, ip_address=?, updated_by=?
    WHERE id=1`,
    [
      site_name,
      admin_name,
      user_image,
      facebook,
      instagram,
      twitter,
      telegram,
      youtube,
      linkedin,
      email,
      email2,
      whatsapp,
      mobile,
      mobile2,
      address,
      address2,
      abouttitle,
      aboutSubtitle,
      aboutTagline,
      aboutimg,
      aboutimg_title,
      aboutimg_alt,
      aboutdec,
      homeslider_title,
      homeslider_subtitle,
      homeslider_tagline,
      yearsOf_experience,
      happy_customers,
      completed_construction,
      logo,
      logoimg_title,
      logoimg_alt,
      footerlogo,
      footerlogo_title,
      footerlogo_alt,
      favicon,
      copyright,
      footer_content,
      address_map,
      terms_condition,
      return_policy,
      privacy_policy,
      meta_title,
      meta_keyword,
      meta_description,
      ip_address,
      updated_by,
    ]
  );
};
